

COUNTRYLIST = {"所罗门群岛": "Solomon Islands",
               "圣文森特和格林纳丁斯": "Saint Vincent and the Grenadines",
               "刚果": "Congo",
               "捷克共和国": "Czech Republic",
               "贝宁": "Benin",
               "圣多美和普林西比": "Sao Tome and Principe",
               "圣皮埃尔和密克隆": "St Pierre and Miquelon",
               "埃及": "Egypt",
               "俄罗斯联邦": "The Russian Federation",
               "萨巴": "Saba",
               "冈比亚": "Gambia",
               "马提尼克": "Martinique",
               "英属维尔京群岛": "British Virgin Islands",
               "也门共和国": "Yemen Republic",
               "科特迪瓦": "Ivory Coast",
               "佛得角": "Cape Verde",
               "斯洛伐克": "The Slovak Republic",
               "亚美尼亚": "Armenia",
               "马绍尔群岛": "Marshall Islands",
               "阿尔巴尼亚": "Albania",
               "比利时": "Belgium",
               "海地": "Haiti",
               "马来西亚": "Malaysia",
               "伊拉克": "Iraq",
               "葡萄牙": "Portugal",
               "津巴布韦": "Zimbabwe",
               "伊朗": "Iran",
               "洪都拉斯": "Honduras",
               "阿曼": "Oman",
               "中非共和国": "Central African Republic",
               "布隆迪": "Burundi",
               "荷属安地列斯群岛": "Netherlands Antilles Islands",
               "巴勒斯坦": "Palestine",
               "巴拿马": "Panama",
               "秘鲁": "Peru",
               "立陶宛": "Lithuania",
               "加那利群岛": "Canary Islands",
               "智利": "Chile",
               "新加坡": "Singapore",
               "卡塔尔": "Qatar",
               "利比亚": "Libya",
               "萨摩亚": "Samoa",
               "诺福克岛": "Norfolk Island",
               "墨西哥": "Mexico",
               "阿塞拜疆": "Azerbaijan",
               "缅甸": "Myanmar",
               "中国香港": "Hong Kong, China",
               "柬埔寨": "Cambodia",
               "盖比群岛": "Gaby Islands",
               "塞尔维亚": "Serbia",
               "巴西": "Brazil",
               "阿富汗": "Afghanistan",
               "日本": "Japan",
               "格鲁吉亚": "Georgia",
               "巴基斯坦": "Pakistan",
               "爱沙尼亚": "Estonia",
               "哥斯达黎加": "Costa Rica",
               "毛里塔尼亚": "Mauritania",
               "马尔代夫": "Maldives",
               "土布艾群岛": "Tubuai Islands",
               "匈牙利": "Hungary",
               "蒙特塞拉特": "Montserrat",
               "基里巴斯": "Kiribati",
               "尼日尔": "Niger",
               "以色列": "Israel",
               "拉脱维亚": "Latvia",
               "文莱": "Brunei",
               "哈萨克斯坦": "Kazakhstan",
               "波兰": "Poland",
               "安道尔": "Andorra",
               "卢森堡": "Luxembourg",
               "安提瓜和巴布达": "Antigua and Barbuda",
               "塞拉利昂": "Sierra Leone",
               "英国": "The United Kingdom",
               "梵蒂冈城国": "Vatican City State",
               "印度": "India",
               "毛里求斯": "Mauritius",
               "斯洛文尼亚": "Slovenia",
               "韩国": "South Korea",
               "古巴": "Cuba",
               "希腊": "Greece",
               "蒙古": "Mongolia",
               "纳米比亚": "Namibia",
               "乍得": "Chad",
               "摩纳哥": "Monaco",
               "孟加拉国": "Bangladesh",
               "埃塞俄比亚": "Ethiopia",
               "丹麦": "Danmark",
               "库克群岛": "The Cook Islands",
               "挪威": "Norway",
               "哥伦比亚": "Colombia",
               "格林纳达": "Grenada",
               "摩洛哥": "Morocco",
               "德国": "Germany",
               "斯里兰卡": "Sri Lanka",
               "苏丹": "Sudan",
               "汤加": "Tonga",
               "澳大利亚": "Australia",
               "新西兰": "New Zealand",
               "叙利亚": "Syrian",
               "突尼斯": "Tunisia",
               "新喀里多尼亚": "New Caledonia",
               "阿根廷": "Argentina",
               "阿尔及利亚": "Algeria",
               "南非": "South Africa",
               "奥地利": "Austria",
               "乌干达": "Uganda",
               "特立尼达和多巴哥": "Trinidad and Tobago",
               "喀麦隆": "Cameroun",
               "塞舌尔": "Seychelles",
               "苏里南": "Suriname",
               "梅利利亚": "Melilla",
               "保加利亚": "Bulgaria",
               "不丹": "Bhutan",
               "东帝汶": "Timor-Leste",
               "多米尼亚共和国": "The Dominican Republic",
               "乌拉圭": "Uruguay",
               "波多黎各": "Puerto Rico",
               "委内瑞拉": "Venezuela",
               "巴布亚新几内亚": "Papua New Guinea",
               "瑞士": "Switzerland",
               "玻利维亚": "Bolivia",
               "特克斯和凯科斯群岛": "The Turks and Caicos Islands",
               "西班牙": "Spain",
               "摩尔多瓦": "Moldova",
               "加纳": "Ghana",
               "阿联酋": "The United Arab Emirates",
               "圭亚那": "Guyana",
               "坦桑尼亚": "Tanzania",
               "尼日利亚": "Nigeria",
               "密克罗尼西亚联邦": "Federated States of Micronesia",
               "尼加拉瓜": "Nicaragua",
               "多米尼加共和国": "The Dominican Republic",
               "法罗群岛": "Faroe Islands",
               "塔吉克斯坦": "Tajikistan",
               "乌兹别克斯坦": "Uzbekistan",
               "土库曼斯坦": "Turkmenistan",
               "马里": "Mali",
               "吉尔吉斯斯坦": "Kyrgyzstan",
               "格陵兰": "Greenland",
               "瑞典": "Sweden",
               "开曼群岛": "The Cayman Islands",
               "白俄罗斯": "Belarus",
               "多哥": "Togo",
               "法国": "France",
               "罗马尼亚": "Romania",
               "圣卢西亚": "Saint Lucia",
               "赞比亚": "Zambia",
               "加蓬": "Gabonese",
               "科威特": "Kuwait",
               "百慕大": "Bermuda",
               "卢旺达": "Rwanda",
               "几内亚": "Guinea",
               "斯威士兰": "Swaziland",
               "法属波利尼西亚": "French Polynesia",
               "塞内加尔": "Senegal",
               "吉布提": "Djibouti",
               "中国澳门": "Macao, China",
               "赤道几内亚": "Equatorial Guinea",
               "直布罗陀": "Gibraltar",
               '圣其茨': '斯":"Saint Kitts and Nevis',
               "泰国": "Thailand",
               "瑙鲁": "Nauru",
               "厄瓜多尔": "Ecuador",
               "老挝": "Lao",
               "荷兰": "Netherlands",
               "伯利兹": "Belize",
               "马耳他": "Malta",
               "越南": "Vietnam",
               "尼泊尔": "Nepal",
               "利比里亚": "Liberia",
               "社会群岛": "Society Islands",
               "约旦": "Jordan",
               "阿鲁巴岛": "Aruba Island",
               "瓦利斯和浮图纳": "Wallis and Futuna",
               "爱尔兰": "Ireland",
               "马拉维": "Malawi",
               "安哥拉": "Angola",
               "图瓦卢": "Tuvalu",
               "塞卜泰": "Saibutai",
               "巴林": "Bahrain",
               "瓦努阿图": "Vanuatu",
               "土耳其": "Turkey",
               "博茨瓦那": "Botswana",
               "圣马丁岛": "Saint Martin",
               "萨尔瓦多": "Salvador",
               "法属圭亚那": "French Guiana",
               "帕劳共和国": "Republic of Palau",
               "土阿莫土群岛": "Tuamotu Archipelago",
               "沙特阿拉伯": "Saudi Arabia",
               "塞浦路斯": "Cyprus",
               "马约特岛": "Mayotte Island",
               "冰岛": "Iceland",
               "莱索托": "Lesotho",
               "巴哈马": "Bahamas",
               "意大利": "Italy",
               "菲律宾": "Philippines",
               "索马里": "Somalia",
               "印度尼西亚": "Indonesia",
               "朝鲜": "North Korea",
               "肯尼亚": "Kenya",
               "留尼汪": "Reunion",
               "巴巴多斯": "Barbados",
               "牙买加": "Jamaica",
               "瓜德罗普": "Guadeloupe",
               "列支敦士登": "Liechtenstein",
               "库腊索岛": "Curacao",
               "巴拉圭": "Paraguay",
               "西撒哈拉": "Western Sahara",
               "马其顿": "Macedonia",
               "黎巴嫩": "Lebanon",
               "斐济": "Fiji",
               "莫桑比克": "Mozambique",
               "厄立特里亚": "Eritrea",
               "圣马力诺": "San Marino",
               "布基纳法索": "Burkina Faso",
               "博内尔": "Bonaire",
               "马克萨斯群岛": "Marquesas Islands",
               "危地马拉": "Guatemala",
               "芬兰": "Finland",
               "科摩罗": "Comoros",
               "克罗地亚": "Croatia",
               "加拿大": "Canada",
               "美国": "The United States",
               "黑山": "Montenegro",
               "中国": "China",
               "民主刚果": "Democratic Republic of the Congo",
               "中国台湾": "Taiwan, China",
               "塞尔维亚和黑山": "Serbia and Montenegro",
               "马达加斯加": "Madagascar",
               "乌克兰": "Ukrain"
               }


UNITLIST = {
    "包": "pound",
    "件": "piece(of clothings)",
    "袋": "bag",
    "盒": "box",
    "个": "piece(by default)",
    "瓶": "bottle",
    "罐": "jar",
    "只": "piece(of animals)",
    "支": "piece(of thin sticks)",
    "块": "chunk",
    "根": "piece(of thick sticks)",
    "条": "bar",
    "双": "pair",
    "套": "package",
    "片": "slice",
    "把": "piece(of umbrellas .etc)"
}

ORDER_STATUS = [
    "waiting",
    "shipped",
    "received",
]